**Develop a model using logistic regression for classification task uaing the dataset make_classification contained in python**

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [3]:
#loading dataset
dataset = make_classification()
dataset

(array([[ 5.44742034e-01,  1.36995077e-03,  7.49591323e-01, ...,
         -2.42423122e-01, -1.32977439e+00,  2.06612177e-01],
        [-9.13355294e-01, -2.08957871e+00,  1.09034599e+00, ...,
          1.58768732e+00,  7.51865977e-01, -1.65634766e-01],
        [-8.31268325e-02, -1.22157831e+00,  8.70477906e-01, ...,
         -1.18804180e+00, -3.93339468e-01, -1.38671811e+00],
        ...,
        [ 1.44000822e+00, -5.11236627e-01,  3.73617279e-01, ...,
         -6.02050216e-01,  4.09076607e-02,  1.46219839e+00],
        [-4.76725761e-02, -2.16124826e+00, -1.35755896e+00, ...,
          1.28392984e-01,  5.33824896e-01,  7.83959364e-01],
        [-5.13828348e-01,  1.21371479e+00, -4.97139258e-01, ...,
          3.62111313e-01, -1.42767249e-01,  3.09923841e-01]]),
 array([0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1,
        0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0,
        1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1,
       

In [4]:
#store features in X and label in Y
X = dataset[0]
y = dataset[1]

In [8]:
#convert X,y to dataframes
X = pd.DataFrame(X)
y = pd.DataFrame(y)

In [9]:
X

0         1         2         3         4         5         6   \
0   0.544742  0.001370  0.749591 -1.190760 -0.030523  1.420599 -0.778865   
1  -0.913355 -2.089579  1.090346  2.601678 -1.423941 -0.960752  1.746745   
2  -0.083127 -1.221578  0.870478  0.083827  0.206678 -0.486048 -0.712612   
3   0.924037  0.962223  0.203180  0.495324  0.239619 -0.193197 -0.794329   
4  -2.109902  0.505441 -1.946828  1.744744  0.035946  1.137097  0.774388   
..       ...       ...       ...       ...       ...       ...       ...   
95  0.807031 -1.404112 -0.240898  0.557692  2.587536 -1.410445  1.300020   
96  0.853707  0.160206  1.340593 -0.322300  0.819457  0.881135  0.323619   
97  1.440008 -0.511237  0.373617 -0.240254  1.432325 -0.311306 -1.931619   
98 -0.047673 -2.161248 -1.357559 -1.245417  1.526521 -0.200782 -0.047970   
99 -0.513828  1.213715 -0.497139 -1.155001 -1.115921  2.067085  0.652471   

          7         8         9         10        11        12        13  \
0  -0.671205 -1.061039  0.147703 -0.410866  0.224216 -0.806762 -0.482519   
1  -1.862268 -1.291312 -0.548255 -0.610679  0.721072  2.313807  1.432164   
2  -1.151189 -1.125207  0.399373 -1.487025 -0.452266 -1.681886  0.335098   
3   0.221313  0.210829 -0.112160  0.816556  0.425849  1.098726 -1.102117   
4   1.382214  1.735510 -1.277116 -2.506107 -0.659288  0.956940  2.122835   
..       ...       ...       ...       ...       ...       ...       ...   
95  0.725798 -0.040751 -1.561697 -1.284924  0.884745 -1.869936 -1.073626   
96 -1.263006  1.528053 -0.409445 -1.273974  0.823790  0.722207 -0.712162   
97  0.272358 -0.677403  0.461205 -0.311464 -0.160583  0.223955 -1.702397   
98  1.703248 -1.045429  0.128179 -1.201605 -0.480392  0.270613 -0.300768   
99  0.365921 -0.164460 -1.327721  1.445502 -0.525156 -0.410388  0.510865   

          14        15        16        17        18        19  
0  -0.022361  1.084462 -0.724227 -0.242423 -1.329774  0.206612  
1  -2.509646  0.565332 -0.350763  1.587687  0.751866 -0.165635  
2  -1.128062  0.978247 -0.101425 -1.188042 -0.393339 -1.386718  
3  -1.291676 -0.806485  0.256367  0.221254  1.999949 -1.322360  
4  -1.068365 -0.147905 -1.622959 -0.158573 -0.248501  0.609856  
..       ...       ...       ...       ...       ...       ...  
95 -0.699833 -0.619367 -0.595796  0.839221 -0.144096 -1.135122  
96  0.730552  0.831869 -1.140406 -0.509014 -0.398554  0.570745  
97  0.738133 -1.787075 -0.644120 -0.602050  0.040908  1.462198  
98  0.618926 -0.224076 -0.782105  0.128393  0.533825  0.783959  
99  0.955078 -1.646082  1.766008  0.362111 -0.142767  0.309924  

[100 rows x 20 columns]

In [11]:
y

0
0   0
1   0
2   0
3   1
4   1
.. ..
95  1
96  0
97  1
98  1
99  0

[100 rows x 1 columns]

In [13]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 20 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   0       100 non-null    float64
 1   1       100 non-null    float64
 2   2       100 non-null    float64
 3   3       100 non-null    float64
 4   4       100 non-null    float64
 5   5       100 non-null    float64
 6   6       100 non-null    float64
 7   7       100 non-null    float64
 8   8       100 non-null    float64
 9   9       100 non-null    float64
 10  10      100 non-null    float64
 11  11      100 non-null    float64
 12  12      100 non-null    float64
 13  13      100 non-null    float64
 14  14      100 non-null    float64
 15  15      100 non-null    float64
 16  16      100 non-null    float64
 17  17      100 non-null    float64
 18  18      100 non-null    float64
 19  19      100 non-null    float64
dtypes: float64(20)
memory usage: 15.8 KB


In [14]:
X.describe()

0           1           2           3           4           5   \
count  100.000000  100.000000  100.000000  100.000000  100.000000  100.000000   
mean    -0.044362   -0.018867    0.001600    0.068109   -0.183608    0.106799   
std      1.076311    0.977479    1.271481    1.119423    0.981920    1.033188   
min     -2.302197   -2.688735   -3.133031   -2.740476   -2.691386   -2.097417   
25%     -0.928143   -0.544246   -1.070587   -0.750997   -0.875767   -0.530256   
50%      0.012900    0.030887    0.206211    0.163177   -0.220817    0.011804   
75%      0.859946    0.604009    0.962752    0.751830    0.400516    0.863253   
max      2.098824    2.013154    2.471892    2.601678    2.587536    3.173405   

               6           7           8           9           10          11  \
count  100.000000  100.000000  100.000000  100.000000  100.000000  100.000000   
mean     0.003910   -0.025078   -0.098183    0.072232    0.136638   -0.049584   
std      1.064830    1.467058    1.021283    0.794213    0.963800    0.903549   
min     -3.487714   -2.752291   -2.123349   -1.946911   -2.506107   -2.279306   
25%     -0.630806   -1.129609   -0.826146   -0.415896   -0.492813   -0.488026   
50%      0.001181   -0.433309   -0.188329    0.068916    0.259708    0.045924   
75%      0.539124    1.152940    0.535715    0.503818    0.618531    0.603110   
max      3.896748    3.574174    2.652895    2.083912    3.151713    2.109500   

               12          13          14          15          16          17  \
count  100.000000  100.000000  100.000000  100.000000  100.000000  100.000000   
mean     0.055640    0.055925   -0.070223   -0.070858    0.015549   -0.039216   
std      1.086872    1.239160    0.928296    0.994896    1.064576    0.924050   
min     -2.735913   -2.393835   -2.509646   -2.170813   -2.151645   -2.303977   
25%     -0.779484   -0.963835   -0.647389   -0.862482   -0.813345   -0.594213   
50%      0.094312   -0.279022   -0.069656   -0.086610   -0.043145   -0.067832   
75%      0.727185    1.094724    0.732089    0.591724    0.712165    0.635461   
max      3.188422    2.580212    1.931018    2.387738    2.646469    2.634840   

               18          19  
count  100.000000  100.000000  
mean    -0.038707    0.031330  
std      0.945439    0.926522  
min     -2.288356   -2.211097  
25%     -0.576144   -0.637093  
50%     -0.088971    0.118990  
75%      0.535964    0.689811  
max      2.347165    3.167549

In [25]:
#spliting X, y
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


In [26]:
LR = LogisticRegression()

In [27]:
LR.fit(X_train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1183: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression()

In [28]:
y_pred = LR.predict(X_test)

In [29]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      0.90      0.95        10
           1       0.91      1.00      0.95        10

    accuracy                           0.95        20
   macro avg       0.95      0.95      0.95        20
weighted avg       0.95      0.95      0.95        20



In [30]:
cm = confusion_matrix(y_test, y_pred)
cm

array([[ 9,  1],
       [ 0, 10]])